GET http://openapi.foodsafetykorea.go.kr/api/56ceaa92652744248404/COOKRCP01/json/1/3
Accept: application/json

###
GET http://openapi.foodsafetykorea.go.kr/api/56ceaa92652744248404/COOKRCP01/json/1/3?RCP_NM=김치찌개
Accept: application/json

###

